apiVersion: v2
name: arch-chart
description: Arch app

type: application
version: 0.1.0
appVersion: 0.1.7

dependencies:
  - name: postgresql
    version: 9.x.x
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
    tags:
      - arch-database
