replicaCount: 2

ingress:
  enabled: true

image:
  repository: exxbrain/architecture

service:
  type: NodePort
  port: 8000
  basePath: /otusapp/dzakharov
  host: arch.homework

postgresql:
  enabled: true
  fullnameOverride: postgres
  postgresqlUsername: arch
  postgresqlPassword: passwd
  postgresqlDatabase: arch
  postgresqlHost: postgres
  service:
    port: 5432