apiVersion: apps/v1
kind: Deployment
metadata:
  name: architecture-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: architecture-app
  template:
    metadata:
      labels:
        app: architecture-app
    spec:
      containers:
        - name: architecture
          image: exxbrain/architecture:0.0.2
          ports:
            - name: web
              containerPort: 8000
          readinessProbe:
            httpGet:
              port: 8000
              path: /health
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            httpGet:
              port: 8000
              path: /
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 2
