apiVersion: apps/v1
kind: Deployment
metadata:
  name: arch-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: arch-app
  template:
    metadata:
      labels:
        app: arch-app
    spec:
      containers:
        - name: arch
          image: exxbrain/architecture:0.1.6
          ports:
            - name: web
              containerPort: 8000
          env:
            - name: DATABASE_URI
              valueFrom:
                secretKeyRef:
                  name: arch-secret
                  key: DATABASE_URI
            - name: GREETING
              valueFrom:
                configMapKeyRef:
                  name: arch-config
                  key: GREETING
            - name: BASE_PATH
              valueFrom:
                configMapKeyRef:
                  name: arch-config
                  key: BASE_PATH
          readinessProbe:
            httpGet:
              port: 8000
              path: /health
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            httpGet:
              port: 8000
              path: /
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 2
