apiVersion: v1
kind: Service
metadata:
  name: arch-service
spec:
  selector:
    app: arch-app
  ports:
    - protocol: TCP
      port: 9000
      targetPort: web
    - port: 9093
      targetPort: 9001
      protocol: TCP
      name: metrics
  type: NodePort
