apiVersion: v1
kind: ConfigMap
metadata:
  name: arch-config
data:
  GREETING: Hello
  BASE_PATH: {{ .Values.service.basePath }}
  SERVER_PORT: "{{ .Values.service.port }}"
---
apiVersion: v1
kind: Secret
metadata:
  name: arch-secret
type: Opaque
data:
  DATABASE_URI: {{ printf "jdbc:postgresql://%s/%s?user=%s&password=%s&ssl=false" .Values.postgresql.postgresqlHost .Values.postgresql.postgresqlDatabase .Values.postgresql.postgresqlUsername .Values.postgresql.postgresqlPassword | b64enc | quote }}