apiVersion: v1
kind: ConfigMap
metadata:
  name: arch-config
data:
  GREETING: Hello
  BASE_PATH: {{ printf .Values.service.basePath }}
---
apiVersion: v1
kind: Secret
metadata:
  name: arch-secret
type: Opaque
data:
  DATABASE_URI: {{ printf "jdbc:postgresql://postgres/%s?user=%s&password=%s&ssl=false" .Values.postgres.postgresqlDatabase .Values.postgres.postgresqlUsername .Values.postgres.postgresqlPassword | b64enc | quote }}