{{- if .Values.ingress.enabled -}}
{{- $fullName := include "arch-chart.fullname" . -}}
{{- $svcPort := .Values.service.port -}}
{{- if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ $fullName }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
    - host: {{ .Values.service.host }}
      http:
        paths:
          - path: {{ .Values.service.basePath }}($|/)(.*)
            backend:
              serviceName: {{ $fullName }}
              servicePort: {{ .Values.service.port }}
  {{- end }}
